[package]
name = "mnist1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mnist = "0.5"
rand = "0.8"
rand_distr = "0.4"
thiserror = "1.0"
